name: Check CSV flow coverage changes

on:
  pull_request:
    paths:
      - '.github/workflows/csv-coverage-pr-comment.yml'
      - '*/ql/src/**/*.ql'
      - '*/ql/src/**/*.qll'
      - 'misc/scripts/library-coverage/*.py'
      # input data files
      - '*/documentation/library-coverage/cwe-sink.csv'
      - '*/documentation/library-coverage/frameworks.csv'
    branches:
      - main
      - 'rc/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Clone self (github/codeql) head
      uses: actions/checkout@v2
      with:
        path: head
    - name: Clone self (github/codeql) base
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: base
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Download CodeQL CLI
      uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
      with:
        repo: "github/codeql-cli-binaries"
        version: "latest"
        file: "codeql-linux64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Unzip CodeQL CLI
      run: unzip -d codeql-cli codeql-linux64.zip
    - name: Generate CSV files on head and base of the PR
      run: |
        echo "Running generator on ${{github.sha}}"
        PATH="$PATH:codeql-cli/codeql" python head/misc/scripts/library-coverage/generate-report.py ci head head
        mkdir out_head
        cp flow-model-coverage-*.csv out_head/
        cp flow-model-coverage-*.rst out_head/

        echo "Running generator on ${{github.event.pull_request.base.sha}}"
        PATH="$PATH:codeql-cli/codeql" python base/misc/scripts/library-coverage/generate-report.py ci base base
        mkdir out_base
        cp flow-model-coverage-*.csv out_base/
        cp flow-model-coverage-*.rst out_base/
    - name: Upload CSV package list
      uses: actions/upload-artifact@v2
      with:
        name: csv-flow-model-coverage-merge
        path: |
          out_head/flow-model-coverage-*.csv
          out_head/flow-model-coverage-*.rst
    - name: Upload CSV package list
      uses: actions/upload-artifact@v2
      with:
        name: csv-flow-model-coverage-base
        path: |
          out_base/flow-model-coverage-*.csv
          out_base/flow-model-coverage-*.rst
    - name: Check coverage files
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} python head/misc/scripts/library-coverage/compare-files.py out_head out_base comparison.md ${{github.event.pull_request.number}} ${{github.run_id}}
    - name: Upload comparison results
      uses: actions/upload-artifact@v2
      with:
        name: comparison
        path: |
          comparison.md

